language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

sudo: false

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 travis_wait composer install --no-interaction

script:
  - mkdir -p build/logs
  - XDEBUG_MODE=coverage php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
