services:
    terminal42_url_rewrite.listener.insert_tags:
        class: Terminal42\UrlRewriteBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"

    terminal42_url_rewrite.listener.rewrite_container:
        class: Terminal42\UrlRewriteBundle\EventListener\RewriteContainerListener
        arguments:
            - "@router"
            - "%kernel.cache_dir%"
