services:
    terminal42_url_rewrite.rewrite_controller:
        class: Terminal42\UrlRewriteBundle\Controller\RewriteController
        arguments:
            - "@database_connection"
            - "@contao.framework"
