services:
    terminal42_url_rewrite.rewrite_controller:
        class: Terminal42\UrlRewriteBundle\Controller\RewriteController
        arguments:
            - "@database_connection"
            - "@contao.framework"

    terminal42_url_rewrite.rewrite_loader:
        class: Terminal42\UrlRewriteBundle\Routing\UrlRewriteLoader
        arguments:
            - "@database_connection"
        tags:
            - { name: routing.loader }
